import { library } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'
library.add(fas)

export { default as Alert } from './components/Alert'
export { default as AutoComplete } from './components/AutoComplete'
export { default as Button } from './components/Button'
export { default as Icon } from './components/Icon'
export { default as Input } from './components/Input'
export { default as Menu } from './components/Menu'
export { default as Progress } from './components/Progress'
export { default as Tabs } from './components/Tabs'
export { default as Transition } from './components/Transition'
export { default as Upload } from './components/Upload'

export {default as Affix} from './components/Affix'
export {default as Avantar} from './components/Avantar'
export {default as Checkbox} from './components/Checkbox'
export {default as Form } from './components/Form'
export {default as Overlay} from './components/overlay'
export {default as Radio} from './components/Radio'
export {default as RadioGroup } from './components/RadioGroup'
export {default as RecordInput} from './components/RecordInput'
export {default as Select} from './components/Select'
export {default as Switcher} from './components/Switcher'
export {default as Tag} from './components/Tag'
export {default as Tooltip} from './components/Tooltip'
